/* import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// import sessionprovider
import AuthProvider from "./sessionProvider";

import Navbar from "./components/navbar";

const geist = Geist({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geist.className}>
        <Navbar />
        <AuthProvider>
        <div style={{ padding: "62px" }}>
          {children}
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
 */